### ISSUE TITLE
Temario Oficial

### ISSUE THREAD

**Issue by IoTeacher** [tectijuana/patrones#2]
![temario](https://cloud.githubusercontent.com/assets/2523851/21995911/5936cb68-dbdc-11e6-85aa-7f71d86ce4f7.png)

[Patrones de Diseño GDF-1302 TEMARIO.pdf](https://github.com/tectijuana/patrones/files/709199/Patrones.de.Diseno.GDF-1302.TEMARIO.pdf)

**Comment by IoTeacher** [comment]
[Patrones de Diseño GDF-1302 TEMARIO.pdf](https://github.com/tectijuana/patrones/files/709199/Patrones.de.Diseno.GDF-1302.TEMARIO.pdf)

**Comment by ivanatorresf** [comment]
Patrones de Diseño
Esta asignatura describe los diferentes patrones de diseño que se pueden usar para diseñar soluciones elegantes para resolver los problemas establecidos en los requisitos de un sistema. En concreto, un patrón de diseño es una solución de diseño robusto y fácilmente mantenible que resuelve un gran conjunto de problemas similares. El estudiante debe adquirir la capacidad de saber elegir el patrón de diseño más adecuado para resolver un problema dado, y adaptar dicho patrón de diseño al problema en concreto.

Conclusión.
Los  patrones  de  diseño  permiten  que  una  parte  del  sistema  varié  de  forma  
independiente sin afectar a las demás partes.
Los  patrones  de  diseño  ayudan  a  poder  estructurar  clases  y  objetos  para  poder  
resolver ciertos problemas y con ello poder adaptarlos al contexto de la aplicación. Tal es la 
importancia del uso de patrones de diseño que los principales ambientes de desarrollo como 
NetBeans  ya  contienen  “plug-in’s”  para  aplicar  a  diseños  UML  de  diagramas  de  clases  
patrones de diseño.

**Comment by ivanatorresf** [comment]
## Patrones de Diseño

_Esta asignatura describe los diferentes patrones de diseño que se pueden usar para diseñar soluciones elegantes para resolver los problemas establecidos en los requisitos de un sistema. En concreto, un patrón de diseño es una solución de diseño robusto y fácilmente mantenible que resuelve un gran conjunto de problemas similares. El estudiante debe adquirir la capacidad de saber elegir el patrón de diseño más adecuado para resolver un problema dado, y adaptar dicho patrón de diseño al problema en concreto.___

## Conclusión.

_Los patrones de diseño permiten que una parte del sistema varié de forma
independiente sin afectar a las demás partes.
Los patrones de diseño ayudan a poder estructurar clases y objetos para poder
resolver ciertos problemas y con ello poder adaptarlos al contexto de la aplicación. Tal es la
importancia del uso de patrones de diseño que los principales ambientes de desarrollo como
NetBeans ya contienen “plug-in’s” para aplicar a diseños UML de diagramas de clases
patrones de diseño._

**Comment by IoTeacher** [comment]
![](https://images.cooltext.com/4892927.png)

----

<a href="http://cooltext.com" target="_top"><img src="https://cooltext.com/images/ct_pixel.gif" width="80" height="15" alt="Cool Text: Logo and Graphics Generator" border="0" /></a>
https://www.tutorialspoint.com/design_pattern/index.htm

Y claro nuestro eBook de Patrones de diseño comentado en clase.
