### ISSUE TITLE
Bloque 1 Introducción a diseño de patrones

### ISSUE THREAD

**Issue by IoTeacher** [tectijuana/patrones#3]
Bloque 1 Introducción a diseño de patrones

**Comment by Alemanitt** [comment]
Los patrones de diseño son un conjunto de prácticas de óptimo diseño que se utilizan para abordar problemas recurrentes en la programación orientada a objetos.

El concepto de patrones de diseño fue el resultado de un trabajo realizado por un grupo de 4 personas (Erich Gamma, Richard Helm, Ralph Johnson y John Vlissides, conocidos como "la pandilla de los cuatro") que se publicó en 1995 en un libro titulado "Patrones de diseño: Elementos de software orientado a objetos reutilizables" en el que se esbozaban 23 patrones de diseño.

**Comment by IoTeacher** [comment]
# Antecedentes 

![gamma richard helm ralph johnson y john vlissides](https://cloud.githubusercontent.com/assets/2523851/22489822/809060f4-e7ce-11e6-9317-4d7ece3e7bcb.png)


Los patrones se introducen en 1995 con el libro del llamado "GoF" de Gang of Four (en referencia a la "banda de los cuatro" autores) llamado "Design Patterns ­ Elements of Reusable object­Oriented Software" escrito por Erich

Gamma, Richard Helm, Ralph Johnson y John Vlissides. Este libro constituye la obra de referencia acerca de patrones de diseño.

Libro mas reciente de los GoF es https://www.abebooks.com/servlet/BookDetailsPL?bi=19725778981&searchurl=tn%3Ddesign%2Bpatterns%2Belements%2Bof%2Breusable%2Bobject%2Boriented%2Bsoftware%26sortby%3D17%26an%3Derich%2Bgamma

> Localiza el eBook en nuestro deposito ISC7Drive

**Comment by IoTeacher** [comment]
![](https://cdn.arstechnica.net/wp-content/uploads/2016/07/Screen-Shot-2016-07-29-at-6.34.49-PM-640x261.png)

## Swift leng. programación que usaremos para el patrón MVC

Leer referente a Swift 3 https://swift.org/about/

## Aprende sobre Swift 3, https://developer.apple.com/swift/
## Y Claro http://swiftstub.com

## Ejecuta HELLO WORLD en Swift  y depositalo en nuestro Git del curso
> Los procedimientos estan en youtube o en este documento que hice para UDs.  https://docs.google.com/document/d/1SMBAxlJF0cRDnWbukNTvhD_4G8BMMMkFJVkJAPF3h5w/edit

> Puede ser por  https://swift.org/download/#releases. 
o via swift compiler online 


----

![base_banners_swift_31_ruta-310x165](https://cloud.githubusercontent.com/assets/2523851/22574622/d736defa-e964-11e6-8292-4e08c3cfcbd1.jpg)


# Referencia del lenguaje por Apple.com

https://developer.apple.com/library/prerelease/content/documentation/Swift/Conceptual/Swift_Programming_Language/index.html#//apple_ref/doc/uid/TP40014097

# http://tinyurl.com/isc7swift

# Foro de Swift 3 español 

https://applecoding.com/


# INSTALACION DE SWIFT 3.X EN SU INSTANCIA AWS O LINUX BOX.
## Aqui esta el procedimiento que realice en el Labotarorio D hace unos meses.

![linux-swift-install](https://cloud.githubusercontent.com/assets/2523851/22717644/20ffb526-ed51-11e6-829b-0b1d6ff923b1.jpg)


https://docs.google.com/document/d/1cnBNeNmWyMb9I4PTu7NGm72p8DNSzgWZDniEOQpjnGk/edit

**Comment by IoTeacher** [comment]
# Programas a realizar en Swift 2.5-3

[patrones-programas.pdf](https://github.com/tectijuana/patrones/files/743549/patrones-programas.pdf)

**Comment by IoTeacher** [comment]
![](https://git-for-windows.github.io/img/git_logo.png)

## Deberá haber un DIRECTORIO. PracticasSwift/_**NickNameGitHub**_ para el deposito de los respectivos programas.
##  En Windows estamos usando el Cliente GIT. https://git-for-windows.github.io

**Comment by IoTeacher** [comment]
3-feb _Viernes asistieron 13 compañeros y se hizo el demo de Git usando el software antes mencionado, y claro se corrigen detalles del tutor._

**Comment by IoTeacher** [comment]
# LISTA DE COTEJO PARA AWSEDUCATE  y aplicar su AMI con Swift 3.x en IaaS

**# Evaluación de la actividad es de 20 Puntos por favor no dejarla al último.**

## _Elaboré este video para darle seguimiento al crédito que AWS les asignará a Uds._

[![ITT AWSEducate para estudiantes ISC](http://img.youtube.com/vi/Ooadh7Djv50/0.jpg)](http://www.youtube.com/watch?v=Ooadh7Djv50)


|    APPLE DEVELOPER PATRONES DE DISEÑO    | AWSEDUCATE STUDENT | AMAZON  SWIFT 3.X VM | OBSERVACIONES |
|:----------------------------------------:|:------------------:|:--------------------:|:-------------:|
| ALEMAN LOPEZ SEBASTIAN                   |                     :+1:      |         35.164.253.247             | ✅    |
| ALVARADO RODRIGUEZ JUAN MANUEL           |          👍          |         35.167.153.142             |    |
| ALVAREZ CORRAL MIGUEL ANGEL              |        👍             |           52.40.144.11           |     |
| BARAJAS BENITEZ LUIS FRANCISCO           |            :+1:           |         52.40.79.85| :sleeping:    |
| CASTRO MARIEL RICARDO DANIEL             |          :+1:           |             52.36.235.54          |   |
| CHIPRES CASTELLANOS ANA MARIA            |           👍          |   35.167.107.202                   |    |
| CORREA ALMARAZ VICTOR HUGO               |             :point_up:         |                      |  |
| CRESPO CORONADO JAZMIN ESMERALDA         |           👍          |       54.202.76.168               |     |
| ESPINOZA COVARRUBIAS SILVERIO ALEJANDRO  |             :+1:        |         52.35.37.24           |    |
| ESPINOZA HERNANDEZ JOSE AMADEO           |                    |                      | :sleeping:    |
| FLORES JIMENEZ RENATO                    |          👍           |         52.10.91.218             | :sleeping:    |
| FLORES RUIZ NAYELI                       |               :+1:       |          54.202.182.38            |  :+1:   |
| GARCIA CARDENAS YAMIRA                   |                    |                      | :sleeping:    |
| GARCIA ZUÑIGA ANA KAREN                  |                    |                      | :sleeping:    |
| GASTELUM ALEMAN CRISTOBAL                |                    |                      | :sleeping:    |
| GASTELUM NIEVES CARLOS                   |          :+1:           |         35.164.246.163         |     |
| GONZALEZ ESPARZA LUIS MANUEL             |         :+1:           |     52.39.183.217           | :+1: :    |
| GONZALEZ MENDEZ ULISES DE JESUS          |                    |        35.167.205.181              | :sleeping:    |
| GUERRERO MARTINEZ DANIEL                 |          :+1:             |          54.203.10.202         |     |
| JUAREZ MEDINA YESIFER CINTHYA            |        :+1:            |       35.166.176.116               | :sleeping:    |
| LARDIZABAL RAMIREZ JUAN CARLOS           |           :+1:          |          52.37.172.193            | ✅     |
| LOPEZ VALENZUELA MARCO ANTONIO           |     :+1:                 |       35.167.14.182               |   |
| MENDOZA MARTINEZ BEATRIZ DAYHAN          |     :+1:               |   35.177.152.147                | :sleeping:    |
| NERIA DIAZ ANTHONY EMMANUEL              |         👍            |           50.112.184.209           |     |
| NUÑEZ HARPER IVAN RAEL                   |        :+1:            |           54.202.57.106           |    |
| OCHOA ZUÑIGA KENYA                       |            :+1:        |               35.162.140.179       | :sleeping:    |
| ORTEGA RODRIGUEZ ASHLEY KARINA           |         :+1:             |                 |  :sleeping:    |
| PALACIOS LEE ARLETTE                     |         :+1:            |         52.11.33.224           | :sleeping:    |
| PEREZ CASTELLANOS ALMA KAREN             |                    |                      | :sleeping:    |
| PRECIADO SALMAN FERNANDO                 |              :+1:       |       35.163.185.179               |     |
| RAMIREZ VASQUEZ LUIS FERNANDO            |          :+1:           |           35.161.76.100| |
| REYES GUTIERREZ GAMALIEL                 |                    |      54.202.58.231                | :sleeping:    |
| SALCEDO MORALES JOSE MANUEL              | :+1: | 52.11.123.252 | |
| SANCHEZ CASAS CESAR GABRIEL              |       :+1:              |     54.202.23.79                 |    |
| SANDOVAL LIZARRAGA CHRISTOPHER FRANCISCO |                    |                      | :sleeping:    |
| TORRES FLORES IVAN ADRIAN                |           👍          |           52.38.13.81           | 😃     |
| VEGA VEGA CRISTIAN ALEXIS                |      :+1:               |     54.202.23.11                  |    |
| VILLEGAS CASTILLO OMAR                   |         👍            |           35.165.193.96           |    |
| YOUNG PEREZ NELSON JUNIOR                |       :+1:              |   35.167.223.211              |:+1:  |
|                                          |   :+1: = Aplicado  | :point_up: = Proceso |               |

**Comment by IoTeacher** [comment]
# LISTADO DE PROGRAMAS DE CONSOLA SEGUN NUESTRO EBOOK _**"PROBLEMAS PARA RESOLVER POR COMPUTADORA"**_ (checar deposito ISC7Drive el libro PDF)

|              APPLE DEVELOPER             	| PROBLEMAS PARA RESOLVER POR COMPUTADORA  CONSOLA SWIFT 3.X 	| OBSERVACIONES 	|
|:----------------------------------------:	|:----------------------------------------------------------:	|:-------------:	|
| ALEMAN LOPEZ SEBASTIAN                   	| Capitulo 1. 1 al 10                                        	|               	|
| ALVARADO RODRIGUEZ JUAN MANUEL           	| Capitulo 1. 11 al 20                                       	|       :+1:         	|
| ALVAREZ CORRAL MIGUEL ANGEL              	| Capitulo 1. 21 al 30                                       	|      :+1:            	|
| BARAJAS BENITEZ LUIS FRANCISCO           	| Capitulo 1. 31 al 40                                       	|               	|
| CASTRO MARIEL RICARDO DANIEL             	| Capitulo 1. 41 al 50                                       	|               	|
| CHIPRES CASTELLANOS ANA MARIA            	| Capitulo 1. 51 al 60                                       	|               	|
| CORREA ALMARAZ VICTOR HUGO               	| Capitulo 1. 61 al 70                                       	|               	|
| CRESPO CORONADO JAZMIN ESMERALDA         	| Capitulo 1. 71 al 74 mas 6 del capitulo último             	|               	|
| ESPINOZA COVARRUBIAS SILVERIO ALEJANDRO  	| Capitulo 2. 1-10                                           	|   :+1:             	|
| ESPINOZA HERNANDEZ JOSE AMADEO           	| Capitulo 2. 11-20                                          	|               	|
| FLORES JIMENEZ RENATO                    	| Capitulo 2. 21-30                                          	|               	|
| FLORES RUIZ NAYELI                       	| Capitulo 2.31-40                                           	|         :+1:       	|
| GARCIA CARDENAS YAMIRA                   	| Capitulo 2.41-50                                           	|               	|
| GARCIA ZUÑIGA ANA KAREN                  	| Capitulo 2.51-60                                           	|               	|
| GASTELUM ALEMAN CRISTOBAL                	| Capitulo 2.61-70                                           	|               	|
| GASTELUM NIEVES CARLOS                   	| Capitulo 2.71-80                                           	|    conversion,TrianguloRectangulo,multiplo de 6,conversiones,par impar,probabilidad,enteros N positivo,Sistemas de ecuaciones, Triangulo equilatero, Raices           	|
| GONZALEZ ESPARZA LUIS MANUEL             	| Capitulo 2.81-90                                           	|               	|
| GONZALEZ MENDEZ ULISES DE JESUS          	| Capitulo 2.91-100                                          	|               	|
| GUERRERO MARTINEZ DANIEL                 	| Capitulo 2.101-110                                         	|               	|
| JUAREZ MEDINA YESIFER CINTHYA            	| Capitulo 2.111-120                                         	|               	|
| LARDIZABAL RAMIREZ JUAN CARLOS           	| Capitulo 6.11-15                                           	|               	|
| LOPEZ VALENZUELA MARCO ANTONIO           	| Capitulo 2.121-127                                         	|               	|
| MENDOZA MARTINEZ BEATRIZ DAYHAN          	| Capitulo 3.1-10                                            	|               	|
| NERIA DIAZ ANTHONY EMMANUEL              	| Capitulo 3.21-30                                           	|               	|
| NUÑEZ HARPER IVAN RAEL                   	| Capitulo 3.31-40                                           	|               	|
| OCHOA ZUÑIGA KENYA                       	| Capitulo 3.41-52                                           	|               	|
| ORTEGA RODRIGUEZ ASHLEY KARINA           	| Capitulo 4.1-10                                            	|               	|
| PALACIOS LEE ARLETTE                     	| Capitulo 4. 11-20                                          	|               	|
| PEREZ CASTELLANOS ALMA KAREN             	| Capitulo 4. 21-30                                          	|               	|
| PRECIADO SALMAN FERNANDO                 	| Capitulo 4. 31-34                                          	|               	|
| RAMIREZ VASQUEZ LUIS FERNANDO            	| Capitulo 5. 1-10                                           	|               	|
| REYES GUTIERREZ GAMALIEL                 	| Capitulo 5. 11-20                                          	|               	|
| SALCEDO MORALES JOSE MANUEL              	| Capitulo 5. 21-30                                          	|               	|
| SANCHEZ CASAS CESAR GABRIEL              	| Capitulo 5. 31-40                                          	|               	|
| SANDOVAL LIZARRAGA CHRISTOPHER FRANCISCO 	| Capitulo 5. 41-50                                          	|               	|
| TORRES FLORES IVAN ADRIAN                	| Capitulo 5. 51-60                                          	|               	|
| VEGA VEGA CRISTIAN ALEXIS                	| Capitulo 5. 61-70                                          	|               	|
| VILLEGAS CASTILLO OMAR                   	| Capitulo 5. 71-80                                          	|               	|
| YOUNG PEREZ NELSON JUNIOR                	| Capitulo 5. 81-90                                          	|               	|
| LARDIZABAL RAMIREZ JUAN CARLOS           	| Capitulo 6. 1-10                                           	|               	|

**Comment by IoTeacher** [comment]
![amazon ami](https://cloud.githubusercontent.com/assets/2523851/22763550/7f56f264-ee1a-11e6-8005-983a6701b004.PNG)

**Comment by IoTeacher** [comment]
![](https://static.betazeta.com/www.fayerwayer.com/up/2015/03/Windows-10-960x623.jpg)

# Recordar el Lac C es un problema con el puerto 22. Esta bloqueado
## Solo en Windows para convertir de *.PEM a *.PPK es para este OS no aplica para MAC ni Linux
![llavesita](https://cloud.githubusercontent.com/assets/2523851/22763896/3b314484-ee1c-11e6-87b7-2ccf3a55e336.PNG)



## Los pasos son de primero tomar el *.PEM que nos da AMI Amazon
-  BAJAR  llavefebrero,pem (o su llave personal de su AMI)
-   Bajar PUTTY (full) http://www.chiark.greenend.org.uk/~sgtatham/putty/latest.html?
![1](https://cloud.githubusercontent.com/assets/2523851/22763803/c5d60b66-ee1b-11e6-803a-32069b0d1983.PNG)
![2](https://cloud.githubusercontent.com/assets/2523851/22763811/cb4fbd76-ee1b-11e6-9578-edf112b29d15.PNG)

**Comment by IoTeacher** [comment]
# Recuerda que es muy agradecido tambien hacer desarrollo en su AWS via Android/iOS Apps de Terminal como:

![](https://i.ytimg.com/vi/mafiNbvmZr4/hqdefault.jpg)


![](https://lh4.ggpht.com/kg0-K1XzPkA4IKpXk-qPN6lCGb0JZarMIKr-LUsHMzK6Uq86OAecRHWx7BOXr1c_OQ=h900)

----

![](http://www.zdnet.com/i/story/63/16/000381/isshenter.jpg)

![](https://i2.wp.com/ioshacker.com/wp-content/uploads/2014/01/Prompt-terminal-app.jpg)


# Falta el video de subir modificaciones al Git por Amazon AWS.....

**Comment by IoTeacher** [comment]
# Como conectarnos a Amazon AWS via Terminal Linux/Windows

![comoentrar](https://cloud.githubusercontent.com/assets/2523851/22847943/8e7143bc-efa5-11e6-86a6-7b963ecbb0a9.png)

# Manual de usuario: http://docs.aws.amazon.com/es_es/AWSEC2/latest/UserGuide/AccessingInstances.html

**Comment by IoTeacher** [comment]
# Recordatorio de como conectarnos a AMI AWSEducate via Windows

 [![IMAGE ALT TEXT HERE](http://img.youtube.com/vi/dZyFzUvJQMc/0.jpg)](http://www.youtube.com/watch?v=dZyFzUvJQMc)

# Trabajando con Linux y macOS en AMI AWSEducate 
   [![IAWS Educate](http://img.youtube.com/vi/3xJeGBTm5LE/0.jpg)](http://www.youtube.com/watch?v=3xJeGBTm5LE)


# Git Basico para Taller
   [![GitBasico](http://img.youtube.com/vi/0tOAsxQaaPE/0.jpg)](http://www.youtube.com/watch?v=0tOAsxQaaPE)

**Comment by IoTeacher** [comment]
# TRABAJANDO CON GIT (UBUNTU) 6 MINUTOS


[![ITrabajando con Git en Linux](http://img.youtube.com/vi/https://youtu.be/rg_Ng-7K31c/0.jpg)](http://www.youtube.com/watch?v=https://youtu.be/rg_Ng-7K31c)

**Comment by IoTeacher** [comment]
# Trabajando con Git (Linux)


[![Video ISC](http://img.youtube.com/vi/0tOAsxQaaPE/0.jpg)](http://www.youtube.com/watch?v=0tOAsxQaaPE)
