### ISSUE TITLE
1.1 ¿Qué es un patrón de diseño

### ISSUE THREAD

**Issue by IoTeacher** [tectijuana/patrones#4]
1.1 ¿Qué es un patrón de diseño?
1.2 Diseño de patrones en MVC.
1.3 Describiendo los patrones de diseño.

**Comment by IoTeacher** [comment]
![](https://obl.sites.ku.dk/files/2015/07/activating_students_630.png)

# Participación (párrafo) ¿Define PDD?
En su reflexión porque consideras importante conocer estas técnicas en "Software Development Cycle". _(igual si no programas sea sincero en reconocer la importancia o la negación del mismo)._  Recuerde de basarse en algún tutor/website/libro mencionarlo al terminal la redacción para evitar que repitan la misma consulta sus colegas.

## _Si son tan amables de dar un Emoji a 4 participaciones que aparecen a continuación ..._ (icono superior derecho)

-----

# Subcribirse a www.dzone.com y descargar 
https://dzone.com/articles/design-patterns-thebeginning. _Principios de los PDD_
https://dzone.com/refcardz/design-patterns _los 23 patrones GoF_

# Patrones y Anti-Patrones
https://dzone.com/refcardz/continuous-integration

#Acción con Git
https://dzone.com/refcardz/getting-started-git _para que trabajen eficientemente en GIT_

# Rercordando UML
https://dzone.com/refcardz/getting-started-uml _comprender elementos UML_

# Software developer
https://dzone.com/articles/what-i-wish-i-knew-when-i-started-as-a-software-de?fromrel=true

# Y Swift que tal...
https://dzone.com/refcardz/swift-essentials. _intro a POO de Swift_

**Comment by ramirez-luis** [comment]
### Definición
*"Un patrón de diseño es una descripción de clases y objetos comunicándose entre sí para resolver un problema de diseño general en un contexto particular."*

Antonio. Introducción a los Patrones de Diseño. Codecriticon, 11 de noviembre de 2014, [http://codecriticon.com/introduccion-patrones-diseno/](http://codecriticon.com/introduccion-patrones-diseno/)

### Conclusión
Creo que los Patrones de diseño son importantes porque nos ayudan a resolver los problemas que encontramos comúnmente en los programas que realizamos, facilitándonos el desarrollo y ahorrando tiempo.

**Comment by fernandopreciado** [comment]
## Patrones de Diseño
*"Los patrones de diseño son el esqueleto de las soluciones a problemas comunes en el desarrollo de software. Brindan una solución ya probada y documentada a problemas de desarrollo de software que están sujetos a contextos similares. "*
* https://msdn.microsoft.com/es-es/library/bb972240.aspx

Creo que los patrones son importantes por que permiten resolver problemas basándonos en formas ya hechas por lo cual va a tener cimientos mas estables y el problema se resolverá mas sencillamente sin tanto peligro de que aparezcan otros problemas.

**Comment by arlettelee** [comment]
## Definición
*"Los Patrones de diseño son herramientas para solucionar problemas de Diseño enfocados al desarrollo de software, estos patrones deben ser reusables permitiendo así que sean adaptados a diferentes problemáticas."*

 [Fuente](https://devexperto.com/patrones-de-diseno-software/)


Considero que los patrones de diseños son importantes para lograr ahorrar tiempo al momento de encontrarse con algún problema, tener la seguridad de que ha sido resuelto de la mejor manera y de ser necesario será mas fácil explicar el código.

**Comment by malvarezcorral** [comment]
*"Los patrones de diseño son principios generales de soluciones que aplican ciertos estilos que ayudan a la creación de software." "Es una descripción de un problema y la solución a la que le da el nombre y que se puede aplicar en nuevos contextos. Muchos patrones ayudan a asignar responsabilidades a los objetos."*

__M.C. Juan Carlos Olivares Rojas__ en *http://dsc.itmorelia.edu.mx/~jcolivares/courses/dp07a/patrones.pdf*

Los patrones de diseño son de gran ayuda cuando en el desarrollo de software o de algún proyecto se topa con un problema común, este se encarga de darnos la solución rápida, eficaz y correcta para continuar en el desarrollo.

**Comment by omar-villegas** [comment]
## ¿Qué es un patrón de diseño?

Un design pattern o patrón de diseño consiste en un diagrama de objetos que forma una solución a un problema conocido y frecuente. El diagrama de objetos esta constituido por un conjunto de objetos descritos por clases y las relaciones que enlazan los objetos.

Los patrones responden a problemas de diseño de aplicaciones en el marco de la programación orientada a objetos. Se trata de soluciones conocidas y probadas cuyo diseño proviene de la experiencia de los programadores. No existe un aspecto teórico en los patrones , en especial no existe una formalización.

### Reflexión 

Los patrones de diseños funcionan como soporte a la hora de estar programando para poder tener diferentes vías que puedan tener diferentes opciones , y poder escoger la que sea mas factible y que la puedas usar.

**Bibliografía :** Debrauwer, L. (2012). Patrones de diseño para C#. 1st ed. Barcelona: Eni.

**Comment by ghost** [comment]
# Patrones de diseño
>### *Los Patrones de diseño son herramientas para solucionar problemas de Diseño enfocados al desarrollo de software, estos patrones deben ser reusables permitiendo así que sean adaptados a diferentes problemáticas.*

## Fuente:
[¿que son los patrones de diseño?](http://codejavu.blogspot.com/2013/06/que-son-los-patrones-de-diseno.html) 
## Conclusión 
> #### Los patrones de diseño tienen como objetivo principal dar una solución a problemáticas comunes que se presentan en la etapa de diseño en cualquier metodología de desarrollo de software.

**Comment by salcedojose** [comment]
_"Los patrones de diseño proporcionan los núcleos de soluciones ya hechas que pueden usarse para resolver muchos de los problemas más comunes del software. Algunos problemas de software requieren soluciones que se derivan de los primeros principios. Pero la mayoría de los problemas son similares a los problemas del pasado, y aquellos pueden ser resueltos usando soluciones similares, o patrones."_
Traduccion de:  **McConnell, S., 2004. Code complete, Redmond, WA: Microsoft Press.**

Los patrones de diseño son los recuerdos de generaciones pasadas: soluciones que en su momento dado pudieron ser utiles para las generaciones anteriores, de igual o mayor utilidad para las siguientes. Ya que dan a conocer marcos con los cuales trabajar, facilitan el **desarrollo de software**, especialmente cuando este se realiza en un equipo. La siguiente vez que estemos en problemas sobre como llevar a cabo la codificacion, los patrones ya exsistentes nos pueden ayudar. Inclusive, tal vez creemos otros. :)

**Comment by AshleyOrtega** [comment]
## **Definición**
"Los patrones de diseño son soluciones para problemas típicos y recurrentes que nos podemos encontrar a la hora de desarrollar una aplicación.
Aunque nuestra aplicación sea única, tendrá partes comunes con otras aplicaciones: acceso a datos, creación de objetos, operaciones entre sistemas etc. Patrones de diseño hay muchos. Muchísimos. Y siguen apareciendo patrones nuevos cada poco tiempo. El desarrollo de aplicaciones es una disciplina en constante cambio "
**[Fuente](https://www.genbetadev.com/metodologias-de-programacion/patrones-de-diseno-que-son-y-por-que-debes-usarlos)**

Los patrones de diseños nos ayudan para crear soluciones a diversos probemas. Estos patrones fueron diseñados para poder resolver situaciones que se puedan presentar, basandose en situaciones ya presentadas anteriormente. De esta manera de tiene la certeza de que el patron a utilizar funciona y podra seguir adaptandose segun la situaciones. 
![meow](http://www.hectorbenitez.com/wp-content/uploads/2010/06/patronesdiseno.jpg)

**Comment by elephannt** [comment]
# Patrones de diseño (Corregido usando Markdown).
----
## ¿Qué es un patrón de diseño (Definición de la web)?. 

> **"Los Patrones de diseño son herramientas para solucionar problemas de diseño enfocados al desarrollo de programa, estos patrones deben ser reusables permitiendo así que sean adaptados a diferentes problemas."**
---

## ¿Qué es un patrón de diseño (Definición propia/Conclusión)?. 

> **Los patrones diseñó en mi opinión, como las simulaciones, pueden ser matemáticas, lo podemos ver como ecuaciones que resuelven un problema en específico, como el teorema de pitágoras,nos ayuda a la resolución de triángulos rectángulos, así como puede ver un patrón de diseño para resolver cierto problema, y poder aplicar el mismo patrón para resolver el problema si se vuelve a presentar.**

---

[Fuentes usadas](http://codejavu.blogspot.mx/2013/06/que-son-los-patrones-de-diseno.html)

**Comment by Cinthyajuarez** [comment]
**Patrón de diseño**
---
"Un Patrón de diseño describe un problema que ocurre una y otra vez en nuestro entorno y describe también el núcleo de su solución, de forma que puede utilizarse un millón de veces sin hacer dos veces lo mismo."
[(Félix Prieto, 2008)](https://www.infor.uva.es/~felix/datos/priii/tr_patrones-2x4.pdf)

**Conclusión**
---
Un patrón de diseño ayuda a resolver problemas comunes que se presentan más de una vez ayudando a que con una solución creada se pueda aplicar más de una vez. Esto es muy útil ya que se optimiza el tiempo de trabajo.

**Comment by nayeliflores** [comment]
**¿Que es un patrón de diseño?**
----
"Los patrones del diseño tratan los problemas del diseño que se repiten y que se presentan en situaciones particulares del diseño, con el fin de proponer soluciones a ellas. Por lo tanto, los patrones de diseño son soluciones exitosas a problemas comunes. Existen muchas formas de implementar patrones de diseño. Los detalles de esta implementacion son llamadas estrategias."


Java.ciberaula.com. (2017). Patrones de Diseño en Java - Ciberaula. [online] Available at:
["Qué es un patrón de diseño"](http://java.ciberaula.com/articulo/diseno_patrones_j2ee ) [Accessed 21 Jan. 2017].

**Conclusión**
---
Al haber leído sobre el tema puedo decir que un patrón de diseño es una solución a un "problema" o una situación de diseño  que anteriormente ya se había presentado y ya hay una serie de procedimientos establecidos para llevar a cabo esa solución, este puede utilizarse las veces que sea necesario y por cualquier desarrollador que necesite este patrón, sin necesidad de volver a inventar una solución.

**Comment by renaflores** [comment]
"En principio, puede pensar en un patrón como una manera especialmente inteligente e intuitiva de resolver una clase de problema en particular.  Un patrón abarca una idea completa dentro de un programa, y por lo tanto puede también abarcar las fases de análisis y diseño de alto nivel."

http://arco.esi.uclm.es/~david.villa/pensar_en_C++/vol2/C10.html#idp4971496

Como se lee al principio un patron de diseño es una manera intuitiva de poder resolver cualquier problema en particular, por ello tiene que ver con diversos pasos para poder resolverlo. Esto ayuda en muchos sentidos a mejorar cualquier programa.

**Comment by kenyaochoa** [comment]
"Los patrones de diseño son un conjunto de prácticas de óptimo diseño que se utilizan para abordar problemas recurrentes en la programación orientada a objetos. 
Un patrón de diseño puede considerarse como un documento que define una estructura de clases que aborda una situación particular. Los patrones de diseño se dividen en tres grupos principales:
**Patrones de creación:** Patrón de Fábrica Abstracta, Patrón Constructor, Patrón del Método de Fabricación, Patrón Prototipo, Patrón de Instancia Única (Singleton).
**Patrones estructurales:** Patrón Adaptador, Patrón Puente, Patrón Compuesto, Patrón Decorador, Patrón de Fachada, Patrón de Peso Mosca, Patrón Apoderado.
**Patrones funcionales:** Patrón de Cadena de Responsabilidad, Patrón de Comando, Patrón Intérprete, Patrón Iterador, Patrón Mediador, Patrón Memento, Patrón Observador, Patrón de Estado, Patrón de Estrategia, Patrón del Método Plantilla, Patrón Visitante."

http://es.ccm.net/contents/224-patrones-de-diseno

Los patrones de diseño son practicas que definen la forma o base que llevara la estructura para la optimizacion y  solucion de un problema.

**Comment by luisfbarajas** [comment]
## ¿Que es un patron de diseño?
"Los patrones de diseño son la base para la búsqueda de soluciones a problemas comunes en el   desarrollo de software y otros ámbitos referentes al diseño de interacción o interfaces.  

Un patrón de diseño debe cumplir al menos con los siguientes objetivos  

* Estandarizar el lenguaje entre programadores  
* Evitar perder tiempo en soluciones a problemas ya resueltos o conocidos  
* Crear código reusable (excelente ventaja)"  

>Qué son y para qué sirven los patrones de diseño. (2017). Platzi Blog. Retrieved 27 January 2017, from https://platzi.com/blog/patrones-de-diseno/

***

### Conclusión 
Los PDD es la manera en la que se intenta dar forma a algún proyecto que se este realizando y   poder optimizarlo que quede lo mejor posible en cuanto a código se refiere, ademas nos ayudan a crear   soluciones a diversos problemas

**Comment by ulisesmendez** [comment]
**Un patrón de diseño es una descripción de clases y objetos comunicándose
entre sí adaptada para resolver un problema de diseño general en un
contexto particular.**

Nombre: describe el problema de diseño.

    • El problema: describe cuándo aplicar el patrón.
    • La solución: describe los elementos que componen el diseño, sus relaciones,
    • responsabilidades y colaboración.

Anon, (2017). [online] Available at: http://siul02.si.ehu.es/~alfredo/iso/06Patrones.pdf [Accessed 27 Jan. 2017].
   Un patrón de diseño es prácticamente la estructura o la forma de la solución de un problema.

**Comment by iscgonzalezluis** [comment]
Los patrones de diseño son la base para la búsqueda de soluciones a problemas comunes en el desarrollo de software y otros ámbitos referentes al diseño de interacción o interfaces. Un patrón de diseño resulta ser una solución a un problema de diseño.

**Comment by alejandro-espinoza** [comment]
_Los Patrones de diseño son herramientas para solucionar problemas de Diseño enfocados al desarrollo de software, estos patrones deben ser reusables permitiendo así que sean adaptados a diferentes problemáticas._

_Cuando hablamos de problemáticas nos referimos a condiciones o problemas reiterativos en el desarrollo de software donde la solución se encuentra identificada mediante la aplicación de una serie de pasos, adaptando el sistema a una estructura definida por un patrón, garantizando que esta solución pueda ser aplicada cuantas veces sea necesario en circunstancias similares, evitando así la búsqueda de otras soluciones cuando estas ya se han dado anteriormente...
Existen varios patrones de diseño popularmente conocidos, los cuales se clasifican como se muestra a continuación:_
- **Patrones Creacionales:** _Giran en torno a la creación de Objetos._
- **Patrones Estructurales:** _Se enfocan en la estructura de clases y objetos que las componen._
- **Patrones de Comportamiento:** _Definen el modo en que las clases y objetos son relacionados, el comportamiento he interacción entre ellos._

**Fuente:**
http://codejavu.blogspot.mx/2013/06/que-son-los-patrones-de-diseno.html

Un patrón se diseño sirve para realizar una solución con una estructura definida para así lograra que sea más optima.

**Comment by elephannt** [comment]
# Patrones de diseño.
----
## Que es un patrón de diseño (Definición de la web)?. 

> **"Los Patrones de diseño son herramientas para solucionar problemas de diseño enfocados al desarrollo de programa, estos patrones deben ser reusables permitiendo así que sean adaptados a diferentes problemas."**
---

## Que es un patrón de diseño (Definición propia)?. 

> **Los patrones diseñó en mi opinión, como las simulaciones, pueden ser matemáticas, lo podemos ver como ecuaciones que resuelven un problema en específico, como el teorema de pitágoras,nos ayuda a la resolución de triángulos rectángulos, así como puede ver un patrón de diseño para resolver cierto problema, y poder aplicar el mismo patrón para resolver el problema si se vuelve a presentar.**

---

[Fuentes usadas](http://codejavu.blogspot.mx/2013/06/que-son-los-patrones-de-diseno.html)

**Comment by nelsonnyp** [comment]
WEB:
¿Qué son los patrones de diseño?

Los patrones de diseño son soluciones para problemas típicos y recurrentes que nos podemos encontrar a la hora de desarrollar una aplicación.

Aunque nuestra aplicación sea única, tendrá partes comunes con otras aplicaciones: acceso a datos, creación de objetos, operaciones entre sistemas etc. En lugar de reinventar la rueda, podemos solucionar problemas utilizando algún patrón, ya que son soluciones probadas y documentadas por multitud de programadores.

PERSONAL: Lo que entendió de patrón de diseño puede ser un segmento de programa o alguna estructura que se repite varias veces en un programa, el cual se puede reutilizar para darle un enfoque  al deseado o, a lo queramos desarrollar o crear.

https://www.genbetadev.com/metodologias-de-programacion/patrones-de-diseno-que-son-y-por-que-debes-usarlos

**Comment by cristobalGA** [comment]
# Patrones de diseño

>  Un patrón de diseño es:
> - Una solución estándar para un problema común de programación.
> - Una técnica para flexibilizar el código haciéndolo satisfacer ciertos criterios.
> - Un proyecto o estructura de implementación que logra una finalidad determinada.
> - Un lenguaje de programación de alto nivel.
> - Una manera más práctica de describir ciertos aspectos de la organización de un programa.
> - Conexiones entre componentes de programas.
> - La forma de un diagrama de objeto o de un modelo de objeto. 

[http://mit.ocw.universia.net/6.170/6.170/f01/pdf/lecture-12.pdf](url)

# Cristobal Gastelum Alemán
Patrones de diseño es la estructura del software con un propósito especifico para resolver un problema que satisface lo requerido.

**Comment by gammarg** [comment]
# Patrones de diseño

> “Los patrones de diseño son el esqueleto de las soluciones a problemas comunes en el desarrollo de software.”

En otras palabras, brindan una solución ya probada y documentada a problemas de desarrollo de software que están sujetos a contextos similares. Debemos tener presente los siguientes elementos de un patrón: su nombre, el problema (cuando aplicar un patrón), la solución (descripción abstracta del problema) y las consecuencias (costos y beneficios).
[https://msdn.microsoft.com/es-es/library/bb972240.aspx](url)

## Gamaliel Reyes
Los patrones son base y guía para resolver problemas repetitivos o comunes que nos pueden pasar a todos en general en el desarrollo de software.
Son importantes ya que nos ayudan a solucionar problemas que alguien mas ya tuvo, también ayuda guiándonos, facilitando y mejorando nuestros proyectos. 
Estos nos ayudan con diferentes aspectos de nuestros proyectos, desde un inicio de cero, ayudándonos con una estructura que ya tengamos, y optimizando alguno que ya tengamos completo.

**Comment by BeatrizMendoza** [comment]
# Patrón de diseño

De acuerdo a Christopher Alexander *"Cada patrón describe un problema que ocurre una y otra vez en nuestro entorno, así como la solución a ese problema, de tal modo que se puede aplicar esta solución un millón de veces sin hacer los mismo dos veces"*

Ademas se determinan 4 elementos esenciales de un patrón de diseño:
- **El nombre** de patrón que nos permite conocer rápidamente de que trata y reutilizarlo para nuevos diseños.
- **El problema** explica a detalle cuando se aplica el patrón así como las condiciones necesarias para que este se use
- **La solución** menciona los elementos que constituyen el diseño, sus relaciones, responsabilidades y colaboraciones, nos proporciona una plantilla que puede aplicarse a diversas situaciones.
- **Las consecuencias** son tanto las ventajas como los inconvenientes de usar el patrón. Ademas puede tratar temas como el lenguaje e implementación.

En conclusión los patrones nos servirán de guía para identificar problemas y su solución de acuerdo a un patrón ya establecido, si bien no incluirán a detalle la solución los patrones son elementos flexibles que pueden adaptarse al problema que estemos presentando, conforme mas soluciones se identifiquen se pueden desarrollar nuevos patrones.

**Comment by iscgonzalezluis** [comment]
# ¿Qué es un Patrón de Diseño?
---
see [msdn](https://msdn.microsoft.com/es-es/library/bb972240.aspx)



> 
“Los patrones de diseño son el esqueleto de las soluciones a problemas comunes en el desarrollo de software.”

En otras palabras, brindan una solución ya probada y documentada a problemas de desarrollo de software que están sujetos a contextos similares. Debemos tener presente los siguientes elementos de un patrón: su nombre, el problema (cuando aplicar un patrón), la solución (descripción abstracta del problema) y las consecuencias (costos y beneficios).

## Definición propia (conlusión)
A mi entender un patrón de diseño es la solución para problemas de desarrollo de software que ya están resueltos. Esta ya viene documentada y nos ayuda para poder solucionar nuestro problema si es parecido a esta.


* [Fuente](https://msdn.microsoft.com/es-es/library/bb972240.aspx)

**Comment by cristianvega** [comment]
# ¿Qué es un Patrón de Diseño?

----
##
Consultado en [https://msdn.microsoft.com/es-es/library/bb972240.aspx](https://msdn.microsoft.com/es-es/library/bb972240.aspx)

> Los patrones de diseño son el esqueleto de las soluciones a problemas comunes en el desarrollo de software.
En otras palabras, brindan una solución ya probada y documentada a problemas de desarrollo de software que están sujetos a contextos similares. Debemos tener presente los siguientes elementos de un patrón: su nombre, el problema (cuando aplicar un patrón), la solución (descripción abstracta del problema) y las consecuencias (costos y beneficios).

----
## Se clasifican como se muestra a continuación:

1.-Patrones Creacionales: Inicialización y configuración de objetos.

2.-Patrones Estructurales: Separan la interfaz de la implementación. Se ocupan de cómo las clases y objetos se agrupan, para formar estructuras más grandes.

3.-Patrones de Comportamiento: Más que describir objetos o clases, describen la comunicación entre ellos.

----
# Lo que entendi

Son soluciones, pasos a seguir o un documento con el cual podemos dar solución cuando se presenta un problema al tener que desarrollar software.

**Comment by CastroRicardo** [comment]
## Patrón de Diseño
*Un patrón de diseño es una solución repetible de un problema de ingeniería de software. a diferencia de la mayoría de los programas de soluciones específicas, los patrones de diseño son utilizados en muchos programas. los patrones de diseño no son considerados productos finales; estos son estructuras que pueden ser aplicadas a múltiples situaciones y que pueden ser usadas en tiempo, haciendo una herramienta de software bastante robusto. Porque la velocidad de desarrollo es incrementada cuando se usa un prototipo ya probado, los desarrolladores usando los templates de patrones de diseño pueden mejorar la eficiencia de la codificación y la facilidad de lectura del producto final.*

* [Fuente: Technopedia.com](https://www.techopedia.com/definition/18822/design-pattern)

**Conclusión**

Un patrón de diseño es una estructura base para el desarrollo de software puede ser utilizado como prototipo para el desarrollo de nuevas herramientas. al mismo tiempo apoyan a la facilidad de interpretación del código pues teniendo un formato más estandarizado.

**Comment by jclardizabal** [comment]
## ¿Qué son los patrones de diseño?. 

> **"La programación orientada a objetos (POO) es un paradigma en la que los sistemas se diseñan mediante clases y relaciones entre ellas. Se utilizan conceptos como la herencia, polimorfismo, abstración, encapsulamiento y ocultación.."**

> tienen como objetivo permitir hacer frente a toda constante que posee cualquier aplicación, el cambio, de tal forma que permitan escalar a los sistemas incorporando nuevas funcionalidades y prefiriendo añadir nuevo código a modificar código existente. 

---
fuente: https://www.fdi.ucm.es/profesor/jpavon/poo/2.14PDOO.pdf

## Conclusión
> **"Se reutiliza código, se optimizan tiempos de ejecución y se mejora la forma de programación."
Conocer estas propiedades es importante para programar en un lenguaje orietado a objetos sin embargo no es suficiente para diseñar sistemas que sean fáciles de mantener y que permitan adaptarse a nuevos cambios sin rediseñar los sistemas.**

---

**Comment by nelsonnyp** [comment]
MarkDown:

# WEB:


## ¿Qué son los patrones de diseño?
Los patrones de diseño son soluciones para problemas típicos y recurrentes que nos podemos encontrar a la hora de desarrollar una aplicación.

Aunque nuestra aplicación sea única, tendrá partes comunes con otras aplicaciones: acceso a datos, creación de objetos, operaciones entre sistemas etc. En lugar de reinventar la rueda, podemos solucionar problemas utilizando algún patrón, ya que son soluciones probadas y documentadas por multitud de programadores.

----
## PERSONAL:
 Lo que entendió de patrón de diseño puede ser un segmento de programa o alguna estructura que se repite varias veces en un programa, el cual se puede reutilizar para darle un enfoque al deseado o, a lo queramos desarrollar o crear.


----
##Fuente
* [https://www.genbetadev.com/metodologias-de-programacion/patrones-de-diseno-que-son-y-por-que-debes-usarlos](https://www.genbetadev.com/metodologias-de-programacion/patrones-de-diseno-que-son-y-por-que-debes-usarlos)


Desing:
WEB:
¿Qué son los patrones de diseño?
Los patrones de diseño son soluciones para problemas típicos y recurrentes que nos podemos encontrar a la hora de desarrollar una aplicación.

Aunque nuestra aplicación sea única, tendrá partes comunes con otras aplicaciones: acceso a datos, creación de objetos, operaciones entre sistemas etc. En lugar de reinventar la rueda, podemos solucionar problemas utilizando algún patrón, ya que son soluciones probadas y documentadas por multitud de programadores.

PERSONAL:
Lo que entendió de patrón de diseño puede ser un segmento de programa o alguna estructura que se repite varias veces en un programa, el cual se puede reutilizar para darle un enfoque al deseado o, a lo queramos desarrollar o crear.

Fuente
https://www.genbetadev.com/metodologias-de-programacion/patrones-de-diseno-que-son-y-por-que-debes-usarlos

**Comment by sanchezcesar** [comment]
# Definición patrones de diseño

----
## Web
see [CCM](http://es.ccm.net/contents/224-patrones-de-diseno)

> "Los patrones de diseño son un conjunto de prácticas de óptimo diseño que se utilizan para abordar problemas recurrentes en la programación orientada a objetos. 
Un patrón de diseño puede considerarse como un documento que define una estructura de clases que aborda una situación particular. Los patrones de diseño se dividen en tres grupos principales:

> - Patrones de creación: Patrón de Fábrica Abstracta, Patrón Constructor, Patrón del Método de Fabricación, Patrón Prototipo, Patrón de Instancia Única (Singleton).

> - Patrones estructurales: Patrón Adaptador, Patrón Puente, Patrón Compuesto, Patrón Decorador, Patrón de Fachada, Patrón de Peso Mosca, Patrón Apoderado.

> - Patrones funcionales: Patrón de Cadena de Responsabilidad, Patrón de Comando, Patrón Intérprete, Patrón Iterador, Patrón Mediador, Patrón Memento, Patrón Observador, Patrón de Estado, Patrón de Estrategia, Patrón del Método Plantilla, Patrón Visitante.".

----
## Personal

Los patrones de diseño son una guía de como se debe de resolver los problemas que se puedan llegar a presentar, de esta manera se evita tener reiteraciones con los problemas o situaciones que se puedan presentar

**Comment by AlvRdzJuan** [comment]
## ¿Qué es un Patrón de Diseño?
> "Los patrones de diseño son el esqueleto de las soluciones a problemas comunes en el desarrollo de software. Brindan una solución ya probada y documentada a problemas de desarrollo de software que están sujetos a contextos similares. "
vea [msdn](https://msdn.microsoft.com/es-es/library/bb972240.aspx)
## Conclusion
*Es una propuesta o pasos a seguir, que ya han sido aprobados por la comunidad tecnológica, para resolver problemas en especifico*

**Comment by carlosgastelum** [comment]
# Patron de diseño 

Un patrón de diseño resulta ser una solución a un problema de diseño. Para que una solución sea considerada un patrón debe poseer ciertas características.  Para que una solución sea considerada un patrón debe poseer ciertas características. Una de ellas es que debe haber comprobado su efectividad resolviendo problemas similares en ocasiones anteriores. Otra es que debe ser reutilizable, lo que significa que es aplicable a diferentes problemas de diseño en distintas circunstancias.



Fuente :
https://www.genbetadev.com/metodologias-de-programacion/patrones-de-diseno-que-son-y-por-que-debes-usarlos

En conclusión un patrón puede describir algún suceso que puede ocurrir infinidad de veces en todo lo que nos rodea, así como la manera de solucionarlo, de tal manera que podamos utilizar esa solución infinidad de veces en un futuro sin tener la necesidad de volver a pensarla de nuevo, a su vez un patrón de diseño puede proporcionar catálogos de elementos reusables en el diseño de software.

**Comment by Christopher933** [comment]
## ¿Que es un patron de diseño?
> Un patrón de diseño es una descripción de clases y objetos comunicándose entre sí adaptada para resolver un problema de diseño general en un contexto particular.

>Fuente: 
[Patrones.pdf](http://siul02.si.ehu.es/~alfredo/iso/06Patrones.pdf)


## Conclusión 
> Son la base para la búsqueda de soluciones a problemas comunes en el desarrollo de software y otros ámbitos referentes al diseño.

**Comment by Alemanitt** [comment]
# PATRON DE DISEÑO
El patron de diseño es el  conjunto de prácticas de óptimo diseño que se utilizan para abordar problemas recurrentes en la programación orientada a objetos.


# DEFINICION PROPIA
Es la base para la busqueda de una solucion a un problema  comun en el ambiente de el desarollador de software

http://es.ccm.net/contents/224-patrones-de-diseno

# CONCLUSION
patrones de diseño fue el resultado de un trabajo realizado por un grupo de 4 personas (Erich Gamma, Richard Helm, Ralph Johnson y John Vlissides, conocidos como "la pandilla de los cuatro") que se publicó en 1995 en un libro titulado "Patrones de diseño: Elementos de software orientado a objetos reutilizables" en el que se esbozaban 23 patrones de diseño.

**Comment by jazmincrespocoronado** [comment]
## ¿Que es un patrón de diseño?


Definición de la web

> “Los patrones de diseño son el esqueleto de las soluciones a problemas comunes en el desarrollo de software.”
En otras palabras, brindan una solución ya probada y documentada a problemas de desarrollo de software que están sujetos a contextos similares. Debemos tener presente los siguientes elementos de un patrón: su nombre, el problema (cuando aplicar un patrón), la solución (descripción abstracta del problema) y las consecuencias (costos y beneficios).


> + *Patrones Creacionales:* Inicialización y configuración de objetos.

> + *Patrones Estructurales:* Separan la interfaz de la implementación. Se ocupan de cómo las clases y objetos se agrupan, para formar estructuras más grandes.

> + *Patrones de Comportamiento:* Más que describir objetos o clases, describen la comunicación entre ellos.


Definición propia

>Son soluciones estructuradas ya probadas, las cuales se implementan a los problemas que se tienen comúnmente al desarrollar software o aplicaciones a pesar de que nuestro programa sea único estas soluciones como ya han sido probadas también pueden aplicarse a otras aplicaciones pueden tener partes similares.

Conclusión

>Los patrones de diseño pueden ser muy eficientes ya que nos facilitan solucionar los problemas que tengamos en las aplicaciones que estemos desarrollando o en cualquier otra, y si estas son similares este patrón nos podría servir para solucionar los problemas que puedan surgir es decir sirven para solucionar problemas para cualquier aplicación que sea similar

----
[Enlace1](https://msdn.microsoft.com/es-es/library/bb972240.aspx)
[Enlace2](https://www.genbetadev.com/metodologias-de-programacion/patrones-de-diseno-que-son-y-por-que-debes-usarlos)

**Comment by chipres** [comment]
----
## ¿Qué  son los patrones de diseño?

#### Definición de la web

> "Los Patrones de diseño" son herramientas para solucionar problemas de Diseño enfocados al desarrollo de software, estos patrones deben ser reusables permitiendo así que sean adaptados a diferentes problemáticas.

>#### Se clasifican en:

> - *Creacionales:* Giran en torno a la creación de Objetos.

> - *Estructurales:* Se enfocan en la estructura de clases y objetos que las componen.

> - *De Comportamiento:* Definen el modo en que las clases y objetos son relacionados, el comportamiento he interacción entre ellos.


#### Definición Propia
>Son soluciones para problemas   que nos podemos encontrar a la hora de desarrollar una aplicación.

> - Conclusión
>Un patrón de diseño,es aquel que describe la solución a problemas, que se repiten una y otra vez en nuestros sistemas, de forma que se puede usar esa solución siempre que haga falta,
 siendo así eficientes al utilizarlos.


[Enlace](http://codejavu.blogspot.mx/2013/06/que-son-los-patrones-de-diseno.html)

----

**Comment by danielguerreromartinez** [comment]
¿Qué son los patrones de diseño?

Los patrones de diseño son soluciones para problemas típicos y recurrentes que nos podemos encontrar a la hora de desarrollar una aplicación.

Aunque nuestra aplicación sea única, tendrá partes comunes con otras aplicaciones: acceso a datos, creación de objetos, operaciones entre sistemas etc. En lugar de reinventar la rueda, podemos solucionar problemas utilizando algún patrón, ya que son soluciones probadas y documentadas por multitud de programadores.

fuente : https://www.genbetadev.com/metodologias-de-programacion/patrones-de-diseno-que-son-y-por-que-debes-usarlos

Personal:
Los patrones de diseño son las posibles soluciones a los diversos problemas que pueden llegar a presentarse, al ser un patron generalmente son una serie de pasos que nos ayudan a solucionar dichos problemas.

**Comment by hriosisc** [comment]
**_¿Qué son los patrones de diseño?_**

 Los patrones de diseño son la base para la búsqueda de soluciones a problemas comunes en el desarrollo de software y otros ámbitos referentes al diseño de interacción o interfaces.

Esta definición me parece muy acertada ya que en palabras simples un patrón de diseño es la solución para los problemas más típicos y recurrentes en el diseño y el desarrollo de un proyecto.

Por esta razón aunque nuestro proyecto sea único, el flujo de trabajo y algunos de sus componentes se van a repetir de un proyecto a otro, entonces, en lugar de “inventar el agua tibia” se pueden resolver los problemas utilizando un patrón de diseño.

**Fuente:** _http://www.arweb.com/chucherias/varios/patrones-de-diseno.htm_

Personal:
> Un patrón de diseño es una forma reutilizable de resolver un problema común. ﻿Te ahorran tiempo, te ayudan a estar seguro de la validez de tu código, establecen un lenguaje común.

**Comment by IoTeacher** [comment]
@Alemanitt un poco despistado publico en otro caso

> Los patrones de diseño son un conjunto de prácticas de óptimo diseño que se utilizan para abordar problemas recurrentes en la programación orientada a objetos.

> El concepto de patrones de diseño fue el resultado de un trabajo realizado por un grupo de 4 personas (Erich Gamma, Richard Helm, Ralph Johnson y John Vlissides, conocidos como "la pandilla de los cuatro") que se publicó en 1995 en un libro titulado "Patrones de diseño: Elementos de software orientado a objetos reutilizables" en el que se esbozaban 23 patrones de diseño.

**Comment by IoTeacher** [comment]
Gracias esta participación esta cerrada.

**Comment by irnh99** [comment]
“Los patrones de diseño son el esqueleto de las soluciones a problemas comunes en el desarrollo de software.”
> https://msdn.microsoft.com/es-es/library/bb972240.aspx

**_Conclusion:_**

> Los patrones de diseño facilitan la creación y estructuración de desarrollo de software, y realmente sin un patron, es muy probable que se termine con un software con una menor utilidad, ya que al darle una estructura, no solo se puede plantear mejor como resolver el problema, sino ver para mas a futuro ya sea, desarrollar en plan de algo futuro o permitir por medio de código y, o documentación que el software pueda ser evolutivo, permitiendo le a alguien trabajar con o sobre tu software.
